goal_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :goals
  resources :comments
  resource :session
end

goal_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

goal_app/app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :goal

end

goal_app/app/models/goal.rb
class Goal < ApplicationRecord
  validates :user, :description, presence: true

  belongs_to :user
  has_many :comments

end

goal_app/app/models/user.rb
class User < ApplicationRecord

  after_initialize :ensure_session_token!

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true
  validates :username, uniqueness: true

  has_many :comments
  has_many :goals

  has_many :commented_goals,
    through: :comments,
    source: :goal

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def is_password?(password)
    bc_pass = BCrypt::Password.new(self.password_digest)
    bc_pass.is_password?(password)
  end

  def ensure_session_token!
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if user.is_password?(password)
    nil
  end
end

goal_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def require_user!
    unless signed_in?
      redirect_to new_session_url
    end
  end

  def sign_in(user)
    session[:session_token] = user.reset_session_token!
  end

end

goal_app/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def new
  end

  def create
  end

  def index

  end

  def show

  end

  def edit

  end

  def update

  end

  def destroy

  end

end

goal_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :require_user!, only: [:destroy]

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(user_params[:username], user_params[:password])

    unless user.nil?
      sign_in(user)
      redirect_to goals_url
    else
      flash[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end


end

goal_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def create
    user = User.new(user_params)
    if user.save
      sign_in(user)
      redirect_to goals_url
    else
      flash[:errors] = user.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  def edit

  end

  def show

  end

  def update

  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

goal_app/app/helpers/application_helper.rb
module ApplicationHelper
end

goal_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

goal_app/app/helpers/users_helper.rb
module UsersHelper
end

goal_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/log_in_out' %>
    <%= render 'shared/welcome_message' %>
    <%= render 'shared/errors' %>
    <%= yield %>
  </body>
</html>

goal_app/app/views/shared/_errors.html.erb
<% unless flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end%>
<% end %>

goal_app/app/views/shared/_log_in_out.html.erb
<% if signed_in? %>
  <%= button_to "Sign out", session_url, method: "delete" %>
<% else %>
  <% unless params["controller"] == "sessions" && params["action"] == "new"  %>
    <%= button_to "Sign in", new_session_url, method: "get" %>
  <% end %>
  <%= button_to "Sign up", new_user_url, method: "get" %>
<% end %>

goal_app/app/views/shared/_welcome_message.html.erb
<% if signed_in? %>
<p>Welcome, <%= current_user.username %>!</p>
<% end %>

goal_app/app/views/users/new.html.erb
<h2> New User </h2>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username
  <input type="text" name="user[username]" value="">
  </label>
  <label>Password
  <input type="text" name="user[password]" value="">
  </label>
  <input type="submit" name="" value="Create User">
</form>